name: VM Docker restart

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Restart containers
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euo pipefail
            cd ~/bot/main
            docker compose restart
